banita::Component_Generator
using banita::Component_Generator::generatorsMap = std::unordered_map<String, fnComponentGenerator >
Component_Generator* banita::Component_Generator::instance
std::unordered_map<String, generatorsMap> banita::Component_Generator::mapOfGeneratorMaps
std::unordered_map<String, fnControllerComponentGenerator> banita::Component_Generator::controllerGenerators
banita::Component_Generator::Component_Generator()
Construct a new Component_Generator object. Currently doing a unintended step in order to register new component. Each component should auto-register invoking this instance.
References register_component_generator, banita::Transform_Component::generator, banita::Camera_Component::generator, banita::Light_Component::generator, banita::Model_Component::generator, register_controller, banita::Player_Controller::generator.
Referenced by get_instance.
banita::Component_Generator::~Component_Generator()
Destroy the Component_Generator object and it's maps.
fnComponentGenerator banita::Component_Generator::register_component_generator(String _module, String _type, fnComponentGenerator _generator)
register a new component generator function pointer
_module _type _generator the component generator function pointer that receives
Referenced by Component_Generator.
fnControllerComponentGenerator banita::Component_Generator::register_controller(String _type, fnControllerComponentGenerator _generator)
_type _generator the controller function pointer that receives
Referenced by Component_Generator.
fnControllerComponentGenerator banita::Component_Generator::get_controller(String _type)
Get the controller generator function pointer.
_type fnControllerComponentGenerator
fnComponentGenerator banita::Component_Generator::get_component_generator(String _module, String _type)
Get the component generator function pointer.
_module _type fnComponentGenerator
fnControllerComponentGenerator banita::Component_Generator::get_controller_generator(String _type)
Get the controller generator function pointer.
_type fnControllerComponentGenerator
static Component_Generator* banita::Component_Generator::get_instance()
Get the instance object.
Component_Generator*
References Component_Generator.