banita::Kernel
using banita::Kernel::Task_Set = std::multiset< Task * >
Task_Set banita::Kernel::tasks
Scene* banita::Kernel::scene
Timer banita::Kernel::timer
float banita::Kernel::time
bool banita::Kernel::exit
bool banita::Kernel::isPaused
banita::Kernel::Kernel()
Construct a new Kernel object by default.
banita::Kernel::Kernel(Scene *_scene)
Construct a new Kernel object and store the pointer to the scene received.
_scene
banita::Kernel::~Kernel()
Destroy the Kernel object and destroy the tasks that store.
void banita::Kernel::run()
run the kernel
Referenced by banita::Scene::execute.
void banita::Kernel::pause()
pause the kernel
Referenced by banita::Scene::pause.
void banita::Kernel::stop()
stop the kernel
Referenced by banita::Scene::~Scene, banita::Scene::stop.
void banita::Kernel::add_task(Task &_task)
adds a task to the tasks set
_task
References banita::Task::set_kernel.
void banita::Kernel::add_tasks(Task *_taskArray, Size_t _arraySize)
adds an array of tasks to the current tasks set
_taskArray _arraySize
void banita::Kernel::add_tasks(Task_Set &_tasks)
adds a set of tasks to the current tasks set
_tasks
void banita::Kernel::remove_task(Task &_task)
removes an specific task from the tasks set
_task task to remove
bool banita::Kernel::is_paused()
get the pause state object
true false
Scene* banita::Kernel::get_scene()
Get the scene object.
Scene*
void banita::Kernel::initialize_tasks()
initialize the tasks
void banita::Kernel::execute_tasks()
update the tasks
void banita::Kernel::terminate_tasks()
finalize the tasks
static bool banita::Kernel::task_priority_comparator_lower_than(const Task *_task1, const Task *_task2)
static bool banita::Kernel::task_comparator_greater_than(const Task *_task1, const Task *_task2)
static bool banita::Kernel::task_comparator_lower_or_equal_than(const Task *_task1, const Task *_task2)
static bool banita::Kernel::task_comparator_greater_or_equal_than(const Task *_task1, const Task *_task2)