banita::Transform_Component
using banita::Transform_Component::Transformation_Matrix = Matrix44
Transform_Component* banita::Transform_Component::parent
Transformation_Matrix banita::Transform_Component::local_scale
Transformation_Matrix banita::Transform_Component::local_anchor
Transformation_Matrix banita::Transform_Component::transformation
std::vector<Vector3f> banita::Transform_Component::movementList
bool banita::Transform_Component::visible
banita::Transform_Component::Transform_Component(Entity *_owner)
Construct a new Transform_Component object and store the received entity.
_owner
Referenced by generator.
banita::Transform_Component::~Transform_Component() override
Destroy the Transform_Component object.
bool banita::Transform_Component::initialize() override
true false
bool banita::Transform_Component::update(float _deltaTime) override
_deltaTime true false
bool banita::Transform_Component::parse_property(const String &_name, const String &value) override
_name value true false
bool banita::Transform_Component::is_near_to_coordinate(Vector3f _coordinate, float _tridimensionalDistance, bool _despiseX=false, bool _despiseY=false, bool _despiseZ=false)
returns if a coordinate is nearest to a coordinate than the limit tridimensional distance. It can despise the desired axis
_coordinate _tridimensionalDistance _despiseX _despiseY _despiseZ true false
References get_position.
Referenced by is_near_to_transform.
bool banita::Transform_Component::is_near_to_transform(Transform_Component &_other, float _tridimensionalDistance, bool _despiseX=false, bool _despiseY=false, bool _despiseZ=false)
return if the received transform is nearest to this than the limit tridimensional distance. It can despise the desired axis
_other _tridimensionalDistance _despiseX _despiseY _despiseZ true false
References is_near_to_coordinate, get_position.
Vector3f banita::Transform_Component::get_position()
Get the position vector.
Vector3f
Referenced by is_near_to_coordinate, is_near_to_transform.
glt::Quaternion banita::Transform_Component::get_rotation()
Get the rotation vector.
glt::Quaternion
Matrix44 banita::Transform_Component::get_transformation()
Get the transformation matrix.
Matrix44
Matrix44 banita::Transform_Component::get_local_transformation()
Get the local anchor matrix.
Matrix44
Transform_Component* banita::Transform_Component::get_parent()
Get the parent transform component.
Transform_Component*
void banita::Transform_Component::move(Vector3f &_translation)
move this transform
_translation
Referenced by move.
void banita::Transform_Component::move(std::vector< Vector3f > &_movementList)
move this transform by a movement list
_movementList
References move.
void banita::Transform_Component::add_movement(Vector3f _translation)
add a movement to the accumulated move list
_translation
void banita::Transform_Component::rotate(Vector3f &_rotation)
rotate this transform by the received vector
_rotation
Referenced by rotateX, rotateY, rotateZ.
void banita::Transform_Component::rotate(float _x, float _y, float _z)
rotate this transform by the received values
_x _y _z
void banita::Transform_Component::rotateX(float _rotX)
rotate this transform rotation x component
_rotX
References rotate.
void banita::Transform_Component::rotateY(float _rotY)
rotate this transform rotation y component
_rotY
References rotate.
void banita::Transform_Component::rotateZ(float _rotZ)
rotate this transform rotation z component
_rotZ
References rotate.
void banita::Transform_Component::scale(float _value)
scale this transform by the input value
_value
void banita::Transform_Component::set_position(Vector3f &_position)
Set the transform position to the received vector.
_position
Referenced by set_position, set_positionX, set_positionY, set_positionZ.
void banita::Transform_Component::set_position(float _pX, float _pY, float _pZ)
Set the position to the received values.
_pX _pY _pZ
References set_position.
void banita::Transform_Component::set_positionX(float _pX)
Set the position x to the received value.
_pX
References set_position.
void banita::Transform_Component::set_positionY(float _pY)
Set the position y to the received value.
_pY
References set_position.
void banita::Transform_Component::set_positionZ(float _pZ)
Set the position z to the received value.
_pZ
References set_position.
void banita::Transform_Component::set_visible(bool _visibility)
Set if is visible this transform (and children)
_visibility
bool banita::Transform_Component::get_visibility()
Get the visibility object.
true false
void banita::Transform_Component::reset()
reset the transformation of this component
static Component_sptr banita::Transform_Component::generator(Entity *_entity)
generator of this component
_entity Component_sptr
References Transform_Component.
Referenced by banita::Component_Generator::Component_Generator.