banita::Message
using banita::Message::Properties = std::unordered_map<Int32, Var>
Int32 banita::Message::ID
Properties banita::Message::messageProperties
banita::Message::Message()
banita::Message::Message(Int32 _id)
banita::Message::Message(String _idString)
banita::Message::~Message()
void banita::Message::add_property(String _key, Var &_property)
adds a property from the content of the message and it's hashed value
_key hashed value of the content to add _property current value of the content to add
void banita::Message::remove_property(String &_key)
Removes a property in a located key.
_key
const Variant& banita::Message::get_property(String &_key)
returns a constant refence to a message property
_key Variant&
const Properties& banita::Message::get_properties() const
Get the properties object.
const Properties&
Int32 banita::Message::get_id() const
Get the id object.
Int32
Referenced by banita::Message_Handler::block_message, banita::Message_Handler::unblock_message, banita::Message_Handler::is_message_blocked.
Variant& banita::Message::operator[](const Int32 _key)
operator that returns a property stored in a given _key
_key Variant&
Variant& banita::Message::operator[](const String &_key)
operator that returns a property stored in a given unhashed _key
_key Variant&
banita::Message::operator Int32() const
when an instance of this class is treated as an uint32_t returns the message's id
Int32
banita::Message::operator Properties() const
when an instance of this class is treated as an unordered map <Int32, Var> returns the message properties object
Properties
bool banita::Message::operator==(const Message &_other) const
bool banita::Message::operator !=(const Message &_other) const